### ISSUE TITLE
Players sometimes do not collect money when passing Go

### ISSUE THREAD

**Issue by michaeljfriedman** [LK/monopoly-simulator#9]
When players pass Go as a result of a card (advance to ________), they sometimes do not collect Go money.

**Comment by LK** [comment]
Go money is accounted for in `GameStateChange.change_position(...)`, so it shouldn't have to be accounted for in the Card method at all. Do you have an example of where Go money isn't being collected?

**Comment by michaeljfriedman** [comment]
Yeah you're right. I remember this being an issue when the Go money was accounted for in Engine, but we moved that logic to GameStateChange for this reason.
